<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('index');
Route::get('/home', 'HomeController@home')->name('home');
Route::get('/almacenes/getAll', 'AlmacenController@getAll')->name('allAlmacen');
Route::resource('/almacenes', 'AlmacenController')->middleware('auth');
Route::get('/proveedores/getAll', 'ProveedorController@getAll')->name('allProveedor');
Route::resource('/proveedores', 'ProveedorController')->middleware('auth');
Route::get('/productos/getAll', 'ProductoController@getAll')->name('allProducto');
Route::get('/inventarios/checkStock', 'InventarioController@checkStock')->name('checkStock');
Route::resource('/productos', 'ProductoController')->middleware('auth');
Route::get('/inventarios/getAll', 'InventarioController@getAll')->name('allInventario');
Route::resource('/inventarios', 'InventarioController')->middleware('auth');
Route::get('/compradores/getAll', 'CompradorController@getAll')->name('allComprador');
Route::resource('/compradores', 'CompradorController')->middleware('auth');
Route::get('/vendedores/getAll', 'VendedorController@getAll')->name('allVendedor');
Route::resource('/vendedores', 'VendedorController')->middleware('auth');
Route::get('/clientes/getAll', 'ClienteController@getAll')->name('allCliente');
Route::resource('/clientes', 'ClienteController')->middleware('auth');
Route::get('/tipoPagos/getAll', 'TipoPagoController@getAll')->name('allTipoPago');
Route::resource('/tipoPagos', 'TipoPagoController')->middleware('auth');
Route::get('/compras/getAll', 'CompraController@getAll')->name('allCompra');
Route::get('/compras/comprasMesPDF','CompraController@comprasMesPDF');
Route::post('/compras/devAll', 'CompraController@devAll')->name('devolucionCompra');
Route::resource('/compras', 'CompraController')->middleware('auth');
Route::get('/detallecompras/getAll', 'CompraDetalleController@getAll')->name('allCompraDetalle');
Route::resource('/detallecompras', 'CompraDetalleController')->middleware('auth');
Route::get('/comprasdevolucion/getAll', 'CompraDevolucionController@getAll')->name('allCompraDevolucion');
Route::resource('/comprasdevolucion', 'CompraDevolucionController')->middleware('auth');
Route::get('/detallecomprasdevolucion/getAll', 'CompraDetalleDevolucionController@getAll')->name('allCompraDetalleDevolucion');
Route::resource('/detallecomprasdevolucion', 'CompraDetalleDevolucionController')->middleware('auth');
Route::get('/pedidos/pedidoPDF','PedidoController@PedidoPDF');
Route::get('/pedidos/getAll', 'PedidoController@getAll')->name('allPedido');
Route::resource('/pedidos', 'PedidoController')->middleware('auth');
Route::get('/detallepedidos/getAll', 'PedidoDetalleController@getAll')->name('allCompraDetalle');
Route::get('/ventas/getAll', 'VentaController@getAll')->name('allVenta');
Route::get('/ventas/ventasJabonBañoPDF','VentaController@ventasJabonBañoPDF');
Route::get('/ventas/ventasMenudeoPDF','VentaController@ventasMenudeoPDF');
Route::post('/ventas/devAll', 'VentaController@devAll')->name('devolucionVenta');
Route::resource('/ventas', 'VentaController')->middleware('auth');
Route::get('/detalleventas/getAll', 'VentaDetalleController@getAll')->name('allVentaDetalle');
Route::resource('/detalleventas', 'VentaDetalleController')->middleware('auth');
Route::get('/ventasdevolucion/getAll', 'VentaDevolucionController@getAll')->name('allVentaDevolucion');
Route::get('/ventasdevolucion/devolucionesPDF', 'VentaDevolucionController@devolucionesPDF')->name('allVentaDevolucionPDF');
Route::resource('/ventasdevolucion', 'VentaDevolucionController')->middleware('auth');
Route::get('/detalleventasdevolucion/getAll', 'VentaDetalleDevolucionController@getAll')->name('allVentaDetalleDevolucion');
Route::resource('/detalleventasdevolucion', 'VentaDetalleDevolucionController')->middleware('auth');

Route::get('/informes', 'InformeController@index')->name('informes');
